# Generated by Django 4.1.6 on 2023-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses_id', models.TextField()),
                ('responses', models.TextField()),
                ('section_name', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
