# Generated by Django 4.1.6 on 2023-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatresponses',
            name='int_id',
            field=models.TextField(blank=True),
        ),
    ]
